version: "3.5"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      - TZ=Asia/Seoul
    env_file: .mysql_env
    volumes:
      - /opt/mysql:/var/lib/mysql
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
