server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
      default_batch_fetch_size: 100
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      encoding: utf-8
  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    time-zone: Asia/Seoul
  servlet:
    multipart:
      max-file-size: 10485760 # 10MB
      max-request-size: 104857600 # 100MB

logging:
  level:
    com.bungaebowling.server: DEBUG
    org.hibernate:
      SQL: DEBUG
      orm.jdbc:
        extract: TRACE
        bind: TRACE

# jwt token config
bungaebowling:
  token_exp:
    access: 172800
    refresh: 2592000
  secret: ${TOKEN_SECRET}
  domain: ${DOMAIN}
  api_server_url: ${API_SERVER_URL}

# gmail smtp config
mail:
  host: smtp.gmail.com
  port: 587
  username: ${GMAIL_USERNAME}
  password: ${GMAIL_APPLICATION_PASSWORD}

# aws s3 config
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      endpoint: ${AWS_S3_END_POINT}
      bucket: bungaebowling-img-s3-private
      proxy:
        host: ${PROXY_HOST}
        port: 80
    region:
      static: ap-northeast-2
    stack:
      auto: false

# google map api config
google:
  api:
    places:
      key: ${GOOGLE_MAP_API_KEY}
