server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/bungaebowling_db?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false
  sql:
    init:
      mode: never
      encoding: utf-8
  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    time-zone: Asia/Seoul
  servlet:
    multipart:
      max-file-size: 10485760 # 10MB
      max-request-size: 104857600 # 100MB

logging:
  level:
    com.bungaebowling.server: INFO

# jwt token config
bungaebowling:
  token_exp:
    access: 172800
    refresh: 2592000
  secret: ${TOKEN_SECRET}
  domain: ${DOMAIN}

# gmail smtp config
mail:
  host: smtp.gmail.com
  port: 587
  username: ${GMAIL_USERNAME}
  password: ${GMAIL_APPLICATION_PASSWORD}

# aws s3 config
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: bungaebowling-img-s3
    region:
      static: ap-northeast-2
    stack:
      auto: false
