namespace: default
resources:
  - nginx.yaml
  - mysql.yaml
  - backend.yaml
  - redis.yaml
  - frontend.yaml
  #- ingress.yaml
configMapGenerator:
  - name: nginx
    files:
      - configs/default.conf
  - name: init-db
    files:
      - configs/create.sql
